- descope/auth/types.go
> Revert "Add username to user struct"

- descope/api/client.go
- descope/auth/auth.go
- descope/auth/auth_test.go
- descope/auth/authmock.go
- descope/auth/sdk.go
- descope/auth/types.go
- descope/errors/errors.go
1. Add support for `/v1/auth/me` request to retrieve current user details
2. Added missing `UserID` field to UserResponse
> Added support for Me request

- descope/api/client.go
- descope/auth/auth.go
- descope/auth/auth_test.go
- descope/auth/authmock.go
- descope/auth/sdk.go
- examples/ginwebapp/main.go
- examples/webapp/main.go
- Change logout to logoutAll and use POST method
- Add DeleteCookies method
> Change logout to use post method and add DeleteCookies option

- descope/auth/auth.go
- descope/auth/auth_test.go
- descope/auth/authmock.go
- descope/auth/sdk.go
add ValidateSessionTokens  func
> add ValidateSessionTokens  func

- descope/api/client.go
- descope/api/client_test.go
Add useful headers to each request
> Add useful headers

- descope/api/client.go
> Calculate sdk info only once

- descope/api/client.go
- descope/auth/saml_test.go
fix cases where a nil body will get marshalled after all
+ test
> Fix nil body

- descope/api/client.go
- descope/auth/auth.go
- descope/auth/auth_test.go
- descope/auth/authmock.go
- descope/auth/sdk.go
Remove the delete cookies and add both logout and logoutAll as options
> Have both logout and logoutAll as optinos

- descope/gin/go.mod
- examples/ginwebapp/go.mod
- examples/ginwebapp/go.sum
- examples/ginwebapp/main.go
- examples/webapp/go.mod
- examples/webapp/go.sum
- examples/webapp/main.go
Fix default base url
fixes https://github.com/descope/go-sdk/issues/162
> Fix go.mod

- descope/auth/types.go
- descope/auth/types_test.go
Add issuer support as url, support also projectID alone for backward.
> Add issuer support as url

- descope/gin/api.go
- examples/ginwebapp/main.go
Fix typo in AuthenticationMiddleware
> Fix typo in AuthenticationMiddleware

- descope/api/client.go
- descope/descope.go
- descope/mgmt/sdk.go
- descope/mgmt/user.go
- descope/mgmt/user_test.go
- descope/tests/helpers/helpers.go
- examples/managementcli/main.go
Adds the ability to load a specific user or search for users according to optional tenant and role filters.
> Add load user and search all users functionality

- descope/api/client.go
- descope/mgmt/jwt.go
- descope/mgmt/jwt_test.go
- descope/mgmt/mgmt.go
- descope/mgmt/sdk.go
related to https://github.com/descope/etc/issues/1002
> Update JWT with custom claims using management API 

- descope/api/client.go
- descope/auth/types.go
- descope/mgmt/mgmt.go
- descope/mgmt/permission.go
- descope/mgmt/permission_test.go
- descope/mgmt/sdk.go
- descope/tests/mocks/mgmt/managementmock.go
- examples/managementcli/main.go
Add the ability to create, update delete and load permissions.
> Add permission API

- descope/api/client.go
- descope/auth/types.go
- descope/mgmt/mgmt.go
- descope/mgmt/role.go
- descope/mgmt/role_test.go
- descope/mgmt/sdk.go
- descope/tests/mocks/mgmt/managementmock.go
- examples/managementcli/main.go
Add the ability to `create`, `update`, `delete` and `loadAll` roles.
> Add role APIs

- descope/api/client.go
- descope/auth/auth_test.go
- descope/auth/jwt.go
related to https://github.com/descope/etc/issues/1126
> Expose v2/keys to get jwt public key 

- descope/auth/enchantedlink_test.go
- descope/auth/types.go
fixes https://github.com/descope/etc/issues/1148 + test
> Change identifier to linkID 

- examples/webapp/main.go
After replacing identifier with linkId
> Fix examples compilation problems

- examples/webapp/main.go
- scripts/build/ci/build_go.sh
Make sure that it will fail if one of the builds in this repo fails
> Fix build script

- descope/api/client.go
- descope/auth/types.go
- descope/mgmt/sdk.go
- descope/mgmt/tenant.go
- descope/mgmt/tenant_test.go
- descope/tests/mocks/mgmt/managementmock.go
- examples/managementcli/main.go
Add the ability to load all tenants.
> Add load all tenants functionality

- descope/auth/auth.go
- descope/auth/auth_test.go
- descope/auth/enchantedlink_test.go
- descope/auth/magiclink_test.go
- descope/auth/otp_test.go
- descope/auth/webauthn_test.go
- descope/descope.go
and always returned to the calling function
If not on cookie, it will be the caller function responsibility to manage it fixed relevant tests
> Session jwt is either on cookie

- descope/auth/auth.go
Defaults to 5 seconds
Made it public, so one can change the number
> Add JWT clock skew

- README.md
- descope/mgmt/sdk.go
- descope/mgmt/user.go
- descope/mgmt/user_test.go
- descope/tests/mocks/mgmt/managementmock.go
Add the ability to load a user by JWT subject.
> Add loadByJWTSubject to management API

- descope/mgmt/group.go
- descope/mgmt/group_test.go
- go.mod
- go.sum
Fix group request names to fit API.
> Fix group request names

- README.md
- descope/auth/types.go
- descope/mgmt/group.go
- descope/mgmt/group_test.go
- descope/mgmt/sdk.go
- descope/mgmt/user.go
- descope/mgmt/user_test.go
- descope/tests/mocks/mgmt/managementmock.go
- examples/managementcli/main.go
Rename JWT subject to user ID.
> Rename JWT subject to user ID

- descope/api/client.go
> Fix logs level for do request

- go.mod
- go.sum
> Fix go mod

- descope/auth/auth.go
- descope/auth/auth_test.go
- descope/auth/enchantedlink_test.go
- descope/auth/types.go
- descope/tests/mocks/auth/authenticationmock.go
Extract refresh token from cookie,
Add more mocks functionalities for GetSession(..) function
Add tests.
> Extract refresh token from cookie

- README.md
Add logout functions to README
> Add logout functions to README

- README.md
> Update README.md file to include RateLimit error handling explanation and example

- descope/internal/auth/auth.go
- descope/internal/auth/auth_test.go
Fixes https://github.com/descope/etc/issues/1853
> feat: set SameSite to Strict

- LICENSE
> update license year to 2023

- descope/api/client.go
Revert sso endpoint back to v1.
> Revert sso endpoint back to v1

- README.md
- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
Add the ability to invite users via the management functions.
> Add the ability to invite users

- README.md
- descope/api/client.go
- descope/internal/auth/password.go
- descope/internal/auth/password_test.go
- descope/internal/auth/utils.go
- descope/internal/auth/webauthn_test.go
- descope/sdk/auth.go
- descope/tests/mocks/auth/authenticationmock.go
- descope/types.go
Add remaining password functions:
- SendPasswordReset
- UpdateUserPassword
- ReplaceUserPassword
- GetPasswordPolicy
> Add remaining password functions

- README.md
Fix readme to include pendingRef for GenerateEnchantedLinkForTestUser
> Fix readme to include pendingRef for GenerateEnchantedLinkForTestUser

- README.md
Fixes https://github.com/descope/etc/issues/2416
> Fix typo for export theme

- descope/internal/auth/enchantedlink.go
- descope/internal/auth/enchantedlink_test.go
- descope/internal/auth/magiclink.go
- descope/internal/auth/magiclink_test.go
- descope/internal/auth/otp.go
- descope/internal/auth/otp_test.go
- descope/internal/auth/utils.go
- descope/sdk/auth.go
- descope/tests/mocks/auth/authenticationmock.go
- descope/types.go
- examples/webapp/main.go
Also determine if to add as loginid or not
This breaks compilation from previous SDK
> Add options to merge users in case of phone or email update

- descope/internal/mgmt/user.go
- descope/types.go
related to https://github.com/descope/etc/issues/2448
> Support updating user picture

- README.md
- descope/api/client.go
- descope/internal/mgmt/sso.go
- descope/internal/mgmt/sso_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
Add method to get SSO settings.
https://github.com/descope/etc/issues/2519
https://github.com/descope/etc/issues/1090
> Add method to get SSO settings

- descope/api/client.go
- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
Option to update only a specific attribute
Option to update only user picture
related to https://github.com/descope/etc/issues/2448
+ tests
> Update user properties

- descope/internal/mgmt/sso_test.go
- descope/types.go
Add domain to GetSSOSettings response.
Related to: https://github.com/descope/etc/issues/2519
> Add domain to GetSSOSettings response

- descope/types.go
related to https://github.com/descope/etc/issues/2640
> totp, saml and oauth are now on user directly

- descope/types.go
- descope/types_test.go
Global permission
And per tenant permission
> Add permission helper function on token

- README.md
- descope/internal/mgmt/sso.go
- descope/internal/mgmt/sso_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
related to https://github.com/descope/etc/issues/2700
+ test
> Delete SAML settings

- examples/managementcli/main.go
small fix to the `access-key-update` description
> Fix access-key-update cli description

- descope/client/client.go
- descope/client/config.go
- descope/internal/auth/auth.go
- descope/internal/auth/auth_test.go
Related to: https://github.com/descope/etc/issues/2978
> Add the ability to set cookie same site

- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/types.go
related to https://github.com/descope/etc/issues/2455
+ tests
> Expose verified email/phone on update request

- descope/client/config.go
> fix typo in config comments

- README.md
- descope/api/client.go
- descope/internal/mgmt/tenant.go
- descope/internal/mgmt/tenant_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- examples/managementcli/main.go
Add option to load tenant by ID.
Related to: https://github.com/descope/etc/issues/3248
> Add option to load tenant by ID

- descope/types.go
related to https://github.com/descope/etc/issues/3224
> Add tenant name to usertenant object

- README.md
- descope/api/client.go
- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
related to https://github.com/descope/etc/issues/2288
> Generate an embedded token for user

- README.md
- descope/api/client.go
- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
This reverts commit 111c296f3f8183b2c636fc859c699a0f51e86972.
> Bring back embedded link

- descope/errors.go
expose err in case of user already logged out
> add logout err

- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
+ test 
related to https://github.com/descope/etc/issues/3834
> Add support for verifiedPhone and verifiedEmail

- README.md
Update README.md with embedded links
> Update README.md with embedded links

- README.md
- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
related to https://github.com/descope/etc/issues/4090
+ tests
> Support invite URL from SDK

- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/types.go
+ test 
related to https://github.com/descope/etc/issues/4154
> Search users by phone or emails

- descope/api/client.go
- descope/internal/mgmt/tenant.go
- descope/internal/mgmt/tenant_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
- examples/managementcli/main.go
By name, attributes, domain and more, export and create tenant with custom attributes 
related to https://github.com/descope/etc/issues/4129 
related to https://github.com/descope/etc/issues/3631
+ tests
Note that this will break compilation with previous versions
> Tenant search

- README.md
- descope/api/client.go
- descope/authztypes.go
- descope/internal/mgmt/authz.go
- descope/internal/mgmt/authz_test.go
- descope/internal/mgmt/mgmt.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- examples/managementcli/main.go
Support ReBAC authorization capabilities in the management SDK
> Added authz support for mgmt

- README.md
- descope/sdk/mgmt.go
Improve clone project comment to mention that this action is supported only with pro license or above
> improve clone project comment

- README.md
- descope/api/client.go
- descope/internal/auth/auth.go
- descope/internal/auth/auth_test.go
- descope/sdk/auth.go
- descope/tests/mocks/auth/authenticationmock.go
+tests
related to https://github.com/descope/etc/issues/3078 Added an API call for selecting a tenant and placing it on the jwt as a custom claim
> Select tenant

- descope/types.go
related to https://github.com/descope/etc/issues/4507
> Expose client ID of access key

- README.md
- descope/internal/mgmt/user.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
Both auth SDK and managemenet SDK
related to https://github.com/descope/etc/issues/4501
> Support first middle nad last name user attributes

- README.md
- descope/api/client.go
- descope/internal/mgmt/project.go
- descope/internal/mgmt/project_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/tests/mocks/mgmt/managementmock_test.go
https://github.com/descope/etc/issues/5001
Adds ability to delete a project
> feat(mgmt): delete project

- descope/api/client.go
- descope/client/client.go
- descope/client/config.go
fixes https://github.com/descope/etc/issues/4996
> Add a conf flag to enforce server certificate validation

- descope/api/client.go
- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
On top of the existing add, remove
+ test
related to https://github.com/descope/etc/issues/4886
> Set user roles

- descope/api/client.go
- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- Add support for management API to remove all passkeys for a user
> Add remove all passkeys management API

- README.md
Added tenant custom attributes and search to readme
> Added tenant custom attributes and search to readme

- descope/types.go
Add embedded delivery method
https://github.com/descope/etc/issues/5082
> Add embedded delivery method

- descope/internal/mgmt/project.go
- descope/internal/mgmt/sso_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
- Remove settings from Clone Project response
> Remove settings from Clone Project response

- descope/api/client.go
Adjust sso tenant settings urls.
> Adjust sso tenant settings urls

- descope/api/client.go
> Do not modify default transport if not of type *http.Transport

- README.md
- descope/api/client.go
- descope/internal/mgmt/flow.go
- descope/internal/mgmt/flow_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- examples/managementcli/go.mod
- examples/managementcli/go.sum
- examples/managementcli/main.go
- Add the ability to delete flows by IDs - https://github.com/descope/etc/issues/5360
- Fix some main examples
- Remove bad import
> Add the ability to delete flows

- README.md
> Fix readme SSO link

- descope/api/client.go
- descope/authztypes.go
- descope/internal/mgmt/authz.go
- descope/internal/mgmt/authz_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
Expose the modified targets and resources for local cache control
> Authz GetModified targets and resources

- README.md
- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/types.go
- Update hashed password import APIs
- Update README
> Update hashed password import APIs

- README.md
Fix history location in readme
> Fix history location in readme

- descope/internal/mgmt/tenant.go
- descope/internal/mgmt/tenant_test.go
- descope/types.go
Related to https://github.com/descope/etc/issues/5400
Add Disable JIT provisioning support
> Add Disable JIT provisioning support

- descope/api/client.go
- descope/api/client_test.go
- scripts/lint/.golangci.yml
- scripts/lint/lint.sh
https://github.com/descope/etc/issues/5226#event-11411420436
- Extract region from project ID
-   [x] Tests
-   [x] Documentation (if applicable)
> Extract region from project ID

- README.md
- descope/internal/mgmt/role.go
- descope/internal/mgmt/role_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
- examples/managementcli/main.go
+ tests
+ readme 
related to https://github.com/descope/etc/issues/2563
> Tenant level roles

- README.md
- descope/api/client.go
- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- examples/managementcli/main.go
Add password expiration flag
- [ X] Tests
- [ X] Documentation (if applicable)
> Add password expiration flag

- README.md
- descope/api/client.go
- descope/internal/mgmt/jwt.go
- descope/internal/mgmt/jwt_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
+ test
related to https://github.com/descope/etc/issues/5584
> Add option to impersonate on management sdk

- README.md
- descope/api/client.go
- descope/internal/mgmt/project.go
- descope/internal/mgmt/project_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
- Update API and documentation to use snapshots
- Update README
> Update API and documentation to use snapshots

- README.md
- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/types.go
related to https://github.com/descope/etc/issues/5993
added invite template options 
FYI I changed internal func to get `createUserRequest` instead [long param list](https://refactoring.guru/smells/long-parameter-list)
> invite template options

- README.md
- descope/internal/mgmt/password.go
- descope/internal/mgmt/password_test.go
- descope/sdk/mgmt.go
Fixes https://github.com/descope/etc/issues/6017
- Make tenantID optional
- Minor doc fixes
> Fix password mgmt

- README.md
- descope/sdk/mgmt.go
- descope/types.go
Found through https://github.com/descope/descope-dotnet/pull/16
Minor fixes to serialization and related documentation.
> Fix IdpURL serialization and related documentation

- README.md
fix create tenant readme example
> fix create tenant readme example

- README.md
- descope/internal/mgmt/audit.go
- descope/internal/mgmt/audit_test.go
- descope/types.go
https://github.com/descope/etc/issues/4255
> Audit type enum

- descope/internal/mgmt/audit.go
- descope/types.go
https://github.com/descope/etc/issues/4255
> Add type and actor to audit record

- descope/internal/auth/auth.go
- descope/internal/auth/auth_test.go
- descope/sdk/auth.go
- descope/tests/mocks/auth/authenticationmock.go
Add the ability to logout with a token
fixes: https://github.com/descope/go-sdk/issues/434
> Add the ability to logout with a token

- descope/types.go
- Add support for importing users with PHPass hashes
> Add support for importing users with PHPass hashes

- README.md
- descope/internal/mgmt/tenant.go
- descope/internal/mgmt/tenant_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
This breaks compilation with previous SDK versions
> Support cascade delete of tenants

- README.md
- descope/api/client.go
- descope/internal/mgmt/project.go
- descope/internal/mgmt/project_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
- Add the ability to list all projects in a company
> Add the ability to list all projects in a company

- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
Related to https://github.com/descope/etc/issues/6852
> Add force refresh and get refresh token options in get provider token

- descope/internal/auth/auth.go
related to https://github.com/descope/etc/issues/6933
> Improve error handling on echange key

- README.md
- descope/internal/mgmt/accesskey.go
- descope/internal/mgmt/accesskey_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
Based on https://github.com/descope/go-sdk/pull/449#discussion_r1685709189 comment
> Fix variable name

- README.md
- descope/internal/mgmt/accesskey.go
- descope/internal/mgmt/accesskey_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
Related https://github.com/descope/etc/issues/6938
Adding the description field to accessKey (create and update).
> add accesskey description

- README.md
related to https://github.com/descope/etc/issues/7009
> Patch request inside readme

- README.md
- descope/internal/mgmt/ssoapplication.go
- descope/internal/mgmt/ssoapplication_test.go
- descope/sdk/mgmt.go
- descope/types.go
Related to https://github.com/descope/etc/issues/7014
> Add SAML IDP logout url (+DefaultRelayState)

- descope/internal/mgmt/user.go
- descope/types.go
related to https://github.com/descope/etc/issues/7585
> Allow searching by login ids

- descope/internal/auth/auth_test.go
- descope/internal/auth/jwt.go
fixes https://github.com/descope/etc/issues/7646
> Safe swap of jwks

- README.md
- descope/api/client.go
- descope/internal/auth/auth.go
- descope/internal/auth/auth_test.go
- descope/internal/auth/jwt.go
- descope/sdk/auth.go
- descope/tests/mocks/auth/authenticationmock.go
- descope/types.go
> Add mytenants call

- descope/internal/mgmt/tenant_test.go
- descope/types.go
Added the created time field to load tenant
> add created time for tenant

- descope/api/client.go
Use v2 end point instead of deprecated v1
> Search users on v2 api

- .github/actions/tests/action.yml
- descope/types.go
- Support importing users with passwords hashed using MD5
> Support importing users with passwords hashed using MD5

- descope/sdk/mgmt.go
> Random typos

- README.md
- descope/internal/mgmt/accesskey.go
- descope/internal/mgmt/accesskey_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
> allow edit access keys

- README.md
small fixes in readme so they will work OOTB
> fix access keys readme

- README.md
A few sentences describing the overall goals of the pull request's commits.
> Fix README.md Manage Projects section

- README.md
- descope/api/client.go
- descope/internal/auth/auth.go
- descope/internal/auth/auth_test.go
- descope/sdk/auth.go
- descope/tests/mocks/auth/authenticationmock.go
> Revert "Add option to logout all previous JWTS"

- descope/types.go
related to https://github.com/descope/etc/issues/8242
> Logout other template option

- README.md
- descope/internal/mgmt/jwt.go
- descope/internal/mgmt/jwt_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
And with selected tenant
+ test 
related to https://github.com/descope/etc/issues/8724
> Impersonate with custom claims

- descope/api/client.go
https://github.com/descope/etc/issues/2119
Use new sso setup suite link (v2)
> Use new sso setup suite link

- descope/api/client.go
- descope/internal/mgmt/third_party_application.go
- descope/internal/mgmt/third_party_application_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- add third party app rotate secret
- add third party app patch app
- add third party app get secret
> add third party app additional functions

- descope/api/client.go
- descope/internal/mgmt/fga.go
- descope/internal/mgmt/fga_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
Allow to load the FGA Schema (DSL)
> Load FGA schema

- README.md
- descope/internal/mgmt/tenant.go
- descope/internal/mgmt/tenant_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
https://github.com/descope/etc/issues/2119
Multi SSO - admin link support
** Breaking compiliation **
> Multi SSO - admin link support

- descope/internal/mgmt/project_test.go
- descope/internal/mgmt/user.go
- descope/types.go
Related to https://github.com/descope/etc/issues/7954
> Outbound apps snapshots

- README.md
- descope/api/client.go
- descope/internal/mgmt/sso.go
- descope/internal/mgmt/sso_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
fixes: https://github.com/descope/etc/issues/9770
Multi SSO CRUD support
> Multi SSO CRUD support

- descope/internal/mgmt/sso.go
- descope/internal/mgmt/sso_test.go
- descope/types.go
> Fix load all sso settings

- README.md
- descope/errors.go
- descope/errors_test.go
Resolves https://github.com/descope/etc/issues/9821
- Add additional error handling functions
- Add section about error handling to the README
> Minor improvements to error handling

- descope/types.go
- Add support for importing users with `SHA` password hashes
> Add support for importing users with SHA password hashes

- README.md
- descope/internal/mgmt/sso.go
- descope/internal/mgmt/sso_test.go
- descope/types.go
> Add FGA Mappings to SSO settings

- descope/types.go
Resolves https://github.com/descope/etc/issues/4097
- Add missing OAuth providers
> Add missing OAuth providers

- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/types.go
related to https://github.com/descope/etc/issues/10001
+ test
> Invite with specific user status

- README.md
- descope/api/client.go
- descope/internal/mgmt/jwt.go
- descope/internal/mgmt/jwt_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
related to https://github.com/descope/etc/issues/9294
+ tests
> Stop impersonation call

- descope/internal/mgmt/third_party_application.go
- descope/types.go
also return modified time of consent
fixes https://github.com/descope/etc/issues/10538
> Inbound consent paging

- README.md
- descope/internal/mgmt/jwt.go
- descope/internal/mgmt/user.go
- descope/internal/mgmt/user_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
+ tests 
related to https://github.com/descope/etc/issues/10553
> Allow logout according to types

- descope/api/client.go
- descope/internal/mgmt/flow.go
- descope/internal/mgmt/flow_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
Add run management flow function
> Add run management flow function

- descope/api/client.go
- descope/internal/mgmt/audit.go
- descope/internal/mgmt/audit_test.go
- descope/sdk/mgmt.go
- descope/tests/mocks/mgmt/managementmock.go
- descope/types.go
+ tests 
fixes https://github.com/descope/etc/issues/11488
> Create web audit connector via SDK

- descope/api/client.go
- descope/api/client_test.go
- descope/client/client.go
- descope/client/config.go
related to https://github.com/descope/etc/issues/11350
+ test
> Support external request ID

- descope/types.go
- descope/types_test.go
Fix cases where token subject is custom
Fix audit webhook filter defenition
> Misc fixes

- descope/internal/mgmt/sso_test.go
- descope/types.go
SSO OIDC group mapping support
https://github.com/descope/etc/issues/11866
> SSO OIDC group mapping support

- descope/client/client.go
- descope/client/config.go
- descope/internal/auth/auth.go
- descope/internal/auth/enchantedlink.go
- descope/internal/auth/magiclink.go
- descope/internal/auth/notp.go
- descope/internal/auth/oauth.go
- descope/internal/auth/otp.go
- descope/internal/auth/password.go
- descope/internal/auth/saml.go
- descope/internal/auth/sso.go
- descope/internal/auth/totp.go
- descope/internal/auth/webauthn.go
If they where set as such in the flow END task
Make sure that SDK will properly parse them from the correct place
> Support custom cookie names in SDK level
