descope/auth/auth.go
descope/auth/auth_test.go
descope/auth/enchantedlink_test.go
descope/auth/magiclink_test.go
descope/auth/otp_test.go
descope/auth/webauthn_test.go
descope/descope.go
examples/ginwebapp/main.go
examples/webapp/main.go

Add option to still send it on cookie
Default to header
Samples are on cookie
Related to https://github.com/descope/etc/issues/1095

Move session JWT to auth header

---

descope/auth/totp_test.go
descope/auth/types.go
examples/managementcli/main.go
examples/webapp/main.go

Use loginIDs instead of externalIDs in response user

Use loginIDs instead of externalIDs in response user

---

README.md
descope/client/client.go
descope/client/client_test.go
descope/client/config.go
descope/gin/api.go
descope/internal/auth/auth.go
descope/internal/auth/auth_test.go
descope/sdk/auth.go
descope/sdk/middleware.go
descope/tests/mocks/auth/authenticationmock.go

**_BREAKING CHANGES_**
Session validation and refresh have been split in order to allow more control over session management. 3 new functions have been added with 2 variations each (a total of 6) with a more predictable and straightforward behavior:
- `ValidateSessionWithRequest` - only validates the session - searches for session token in the request
- `ValidateSessionWithToken` - only validates the session - receives token as input
- `RefreshSessionWithRequest` - refreshes a session - searches for session token in the request
- `RefreshSessionWithToken` - refreshes a session - receives token as input
- `ValidateAndRefreshSessionWithRequest` - combines the two, validate and refresh as needed - searches for tokens in the request
- `ValidateAndRefreshSessionWithTokens` - combines the two, …

Split session refresh

---

descope/internal/auth/auth.go
descope/internal/auth/auth_test.go

Both "validate and refresh" functions support a single token behavior:
- If only the `sessionToken` is provided - default to a "validate only" behavior
- If only the `refreshToken` is provided - default to a "refresh only" behavior

Support single token in validate and refresh

---

descope/client/client_test.go
descope/client/config.go
descope/logger/log.go
descope/types.go

When two instance of Descope client are managed in a concurrent  manner, they may create a race condition where one may use the `instanceLogger`, and the other may override it
init logger once
Another approach may be to put a dedicate logger per client
but then this logger will not be available outside the scope of this client, in places like
- `Token` methods
- `AuthenticationMiddleware` (where the client is passed as an argument with as `Authentication` interface, which not exposes the logging method)  
I think that this is a good solution for now, that can be later enhanced according to specific use cases

Init log once

---

descope/api/client.go
descope/client/client.go
descope/client/client_test.go
descope/internal/auth/auth.go
descope/internal/auth/jwt.go
descope/internal/auth/oauth.go
descope/internal/auth/saml.go
descope/internal/mgmt/mgmt.go
descope/sdk/middleware.go

Some small logging alignment I noticed during a previous PR on Descope go-sdk is that some of the log messages are lowercase and some uppercase, same for the error message (all are capital expect one)
this may be probably be automated and enforced with [custom linter](https://golangci-lint.run/contributing/new-linters/), but it may require more effort as well

Logging and error capitalisation alignment

---

README.md
descope/api/client.go
descope/internal/mgmt/sso.go
descope/internal/mgmt/sso_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go

Upgrade management SSO configuration to v2, which now supports the `domain` parameter. This is a **_BREAKING CHANGE_** albeit a minor one - so to speak. A parameter was added. The behavior remains largely the same with the new addition.

Upgrade management sso configuration to v2

---

README.md
descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go
examples/managementcli/main.go

Add the ability to paginate the search user response. This change **breaks** the signature of the function but not behavior. Previous usages before this change were as if `page` was set to `0` (the first page).

Add page to search users

---

README.md
descope/client/client_test.go
descope/internal/auth/auth.go
descope/internal/auth/enchantedlink_test.go
descope/internal/auth/magiclink.go
descope/internal/auth/magiclink_test.go
descope/internal/auth/otp.go
descope/internal/auth/otp_test.go
descope/internal/auth/utils.go
descope/internal/auth/webauthn_test.go
descope/sdk/auth.go
descope/tests/mocks/auth/authenticationmock.go
descope/types.go
examples/ginwebapp/main.go
examples/webapp/main.go

This applies to otp magic link and enchanted link
Use of magix link and otp will break compilation upon upgrading to this version The value is returned upon initiation of the signup/in method and returned in masked format

Return the masked email or address to caller

---

README.md
descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/tests/mocks/mgmt/managementmock_test.go
descope/types.go
descope/types_test.go
examples/importusers/main.go
examples/managementcli/main.go

So one can now create/update/invite a user and have the custom attributes already in place
Assuming those were configured already in the Descope console 
Export the user and role createTime
related to https://github.com/descope/etc/issues/2450
related to https://github.com/descope/etc/issues/299
This PR will break compilation comparing to previous versions

Support custom attributes for user manamgenet SDK

---

.github/actions/lint/action.yml
.github/actions/tests/action.yml
.github/workflows/ci.yml

`{{ github.token }}` is only available in job `steps` and not available in action `with:` so this action fails when running with a non-privileged user.
This fix replaces the use of `github` context with `secrets.GITHUB_TOKEN` which is always available
also fixed other action linting issues 
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context:~:text=token%20authentication.%22-,Note%3A%20This%20context%20property%20is%20set%20by%20the%20Actions%20runner%2C%20and%20is%20only%20available%20within%20the%20execution%20steps%20of%20a%20job.%20Otherwise%2C%20the%20value%20of%20this%20property%20will%20be%20null.,-github.triggering_actor

fix: github token

---

descope/internal/auth/auth.go
descope/internal/auth/auth_test.go

https://github.com/descope/etc/issues/3104
Ensure that the user is associated to tenant before checking roles/permissions

Check associated tenant before checking roles/permissions

---

README.md
descope/api/client.go
descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
examples/managementcli/main.go

Leave new id as empty to remove ID
last login ID cannot be removed
+ tests 
related to https://github.com/descope/etc/issues/2985

Update login ID

---

README.md
descope/internal/mgmt/sso.go
descope/internal/mgmt/sso_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go

https://github.com/descope/go-sdk/issues/293
- Adds the two parameters from `ConfigureSettings` to also be available in `ConfigureMetadata`
- Requires backend support before this is usable in production
- This is a minor **_BREAKING CHANGE_** - existing code that calls `ConfigureMetadata` fail compilation until the values for the two new parameters are provided.

Support domain and redirectURL field when updating SSO metadata URL

---

README.md
descope/internal/auth/password.go
descope/internal/auth/password_test.go
descope/sdk/auth.go
descope/sdk/mgmt.go
descope/tests/mocks/auth/authenticationmock.go

related to https://github.com/descope/etc/issues/3800
Change `ReplaceUserPassword` func signature to support the returned authentication info
- receive a response writer argument (`w`)
- return an authentication info (`*descope.AuthenticationInfo`)
noting that this breaks usage compilation, based on some discussions we conclude to:
- communicate that in next release note
- should not consider this as a major version
if we agree on that, I will communicate this forward to relevant ppl in team

Replace password session

---

descope/types.go

- Add `WebAuthn` and `Password` boolean flags to the `UserResponse` struct that mark if the user can authenticate with theses methods

Add support for new WebAuthn and Password user auth method flags

---

README.md
descope/api/client.go
descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go

Support with both user ID and login ID
related to https://github.com/descope/etc/issues/4121

Logout all devices call

---

descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/types.go

Add the ability to specify invite type - Email / SMS
Related to: https://github.com/descope/etc/issues/4542

Add the ability to specify invite type

---

README.md
descope/api/client.go
descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go

Fixes https://github.com/descope/etc/issues/4462
Add support for batch invite

Add support for batch invite

---

README.md

Fixed syntax error in readme

---

descope/api/client.go
descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go

- Expose user import API (`mgmt/user/import`) for direct use in manual imports or via the `migrate` command line tool

Add user import API

---

README.md
descope/api/client.go
descope/internal/mgmt/project.go
descope/internal/mgmt/project_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go

https://github.com/descope/etc/issues/4524
expose clone project
also added update-name functionality

expose clone project

---

descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go

- Add support for batch user creation with passwords

Add support for batch user creation with passwords

---

README.md
descope/internal/auth/auth.go
descope/internal/auth/auth_test.go
descope/sdk/auth.go
descope/tests/mocks/auth/authenticationmock.go

https://github.com/descope/etc/issues/4847
expose functions to get matched roles / permissions

Get matched roles and permissions

---

descope/api/client.go
descope/api/client_test.go
descope/client/client.go
descope/client/config.go

Fixes https://github.com/descope/etc/issues/4996
- Change default behavior to only skip certificate validation when overriding the server baseURL with the address of a development environment
- Allow clients to decide to override behavior to always or never validate server certificate

Skip certificate validation only for development server baseURLs

---

descope/api/client.go
descope/api/client_test.go

Skip certificate validation for non-domain hostnames by default

Skip certificate validation for non-domain hostnames by default

---

README.md
descope/api/client.go
descope/internal/mgmt/mgmt.go
descope/internal/mgmt/password.go
descope/internal/mgmt/password_test.go
descope/internal/mgmt/tenant.go
descope/internal/mgmt/tenant_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go

add password get / update
add tenant settings get / update
updated readme
add tests

Password & tenant settings api

---

descope/internal/mgmt/project.go
descope/internal/mgmt/project_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
tools/environment/export.go
tools/environment/import.go

- Remove redundant `...Raw` suffix from project `ImportRaw`/`ExportRaw` function names

Remove redundant Raw suffix from Import/Export function names

---

README.md
descope/api/client.go
descope/internal/auth/auth.go
descope/internal/auth/auth_test.go
descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/sdk/auth.go
descope/sdk/mgmt.go
descope/tests/mocks/auth/authenticationmock.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go

Related to: https://github.com/descope/etc/issues/4713
Add user history support for auth and mgmt apis.

Add user history support for auth and mgmt apis

---

descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go

Related to: https://github.com/descope/etc/issues/4713
Fix history param name to be userIDs and not loginIDs

Fix history param name to be userIDs and not loginIDs

---

README.md
descope/internal/mgmt/sso.go
descope/internal/mgmt/sso_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go

Remove redundant redirectUrl function parameter so it will not be confused with the same redirectUrl parameter inside the OIDCSettings parameter.

Remove redundant redirectUrl param

---

README.md
descope/api/client.go
descope/internal/auth/auth.go
descope/internal/auth/oauth.go
descope/internal/auth/oauth_test.go
descope/sdk/auth.go
descope/tests/mocks/auth/authenticationmock.go

Related to https://github.com/descope/etc/issues/5713
- add update user with OAuth
- add tests

Add API to update user OAuth

---

README.md
descope/api/client.go
descope/internal/mgmt/audit.go
descope/internal/mgmt/audit_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go

Add the ability to create audit event

Audit - create event

---

README.md
descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go

Add total users to search all users method.
This breaks compatibility - compilation only.

Add total users to search all users method (breaking)

---

descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/types.go

Related to: https://github.com/descope/etc/issues/6651
Add support for TOTP seed in invite users.

Add support for TOTP seed in invite users

---

README.md
descope/internal/mgmt/accesskey.go
descope/internal/mgmt/accesskey_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go

Related to https://github.com/descope/etc/issues/6798
Adds Permitted IPs to Access Keys

Add Permitted IPs to Access Keys

---

.github/actions/tests/action.yml
descope/internal/auth/enchantedlink.go
descope/internal/auth/enchantedlink_test.go
descope/internal/auth/magiclink.go
descope/internal/auth/magiclink_test.go
descope/internal/auth/otp.go
descope/internal/auth/otp_test.go
descope/internal/auth/utils.go
descope/types.go

- Add support for custom `templateID` in sign up and sign in operations to choose a different messaging template other than the default one when a custom provider is configured.

Add support for custom templateID in sign up and sign in

---

descope/types.go

So we can see which users failed on the invite sent and which not

Expose additional errors on invite batch

---

README.md
descope/api/client.go
descope/authztypes.go
descope/internal/mgmt/fga.go
descope/internal/mgmt/fga_test.go
descope/internal/mgmt/mgmt.go
descope/internal/mgmt/user_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go

This pull request introduces support for Fine-Grained Authorization (FGA) in the Descope SDK. The changes include adding new endpoints, data structures, and methods for managing FGA schemas and relations, as well as performing checks. 
Added 4 new functions under `Management.FGA()`
- `SaveSchema` - Creates a new schema for the project.
- `CreateRelations` - Creates new relations for the project.
- `DeleteRelations` - Deletes relations for the project.
- `Check` - Checks if the given relations are satisfied.

Add FGA API support

---

README.md
descope/api/client.go
descope/internal/auth/auth.go
descope/internal/auth/auth_test.go
descope/sdk/auth.go
descope/tests/mocks/auth/authenticationmock.go

This new function call, will expire all jwts created prior to the one in the request related to https://github.com/descope/etc/issues/8242
+ tests

Add option to logout all previous JWTS

---

README.md
descope/api/client.go
descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go

Adjust CreateTestUser endpoint url + Add SearchAllTest api for searching only test users

Adjust and add test user functionality

---

descope/api/client.go
descope/internal/mgmt/user_test.go

Updates the version for the Management User Add Tenant Roles API. 
With this new version, roles will be added to the tenant even if the user does not have access to the tenant. Access to the tenant will be added.

Management User Add Tenant Roles API upgrade

---

descope/internal/auth/sso.go
descope/internal/auth/sso_test.go
descope/sdk/auth.go
descope/tests/mocks/auth/authenticationmock.go

Multi SSO - allow to pass SSO ID for sso start method, only relevant when using Multi SSO.
This breaks complation.
Related to https://github.com/descope/etc/issues/2119

Multi SSO - allow to pass SSO ID for sso start method (breaks compilation)

---

descope/internal/mgmt/user.go
descope/internal/mgmt/user_test.go
descope/types.go

+ test 
related to https://github.com/descope/etc/issues/8535

Invite template id

---

descope/internal/mgmt/audit.go
descope/internal/mgmt/audit_test.go
descope/types.go
examples/webapp/go.sum
examples/webapp/main.go

Added support for paging audit search results and updated example webapp accordingly
Added support for the setting the "size" and "page" parameters for the `/mgmt/audit/search` API call via the SDK
Fixes: https://github.com/descope/etc/issues/8822

feat: added support for paging audit search results 

---

descope/internal/mgmt/audit.go
descope/internal/mgmt/audit_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go
examples/webapp/main.go
scripts/lint/gitleaks.toml

Resolves: https://github.com/descope/etc/issues/8887
Added a new Audit.SearchAll API which also returns the total number of search results, same as in the User.SearchAll API. Marked the existing Audit.Search method as Deprecated.
Additional minor fixes:
1. feat: renamed option to set paging size by using the `Limit` option instead of the `Size` option to adhere to the same API used in User.SearchAll (breaking change, but breaks a new API which is not in use yet, so not worth "dirtying" the API with unneeded backwards compatibility aliases)
2. chore: added files generated by running the local example to be ignored by gitleaks to avoid false leaks from appearing in pre-commit hooks

feat: added support for returning total number of results in new Audit.SearchAll method

---

README.md
descope/client/client_test.go
descope/internal/mgmt/jwt.go
descope/internal/mgmt/jwt_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go

Supported as part of jwt update flow
+test
fixes https://github.com/descope/etc/issues/8900

Allow updating jwt expiry via SDK

---

descope/api/client.go
descope/api/client_test.go
descope/client/client.go
descope/client/client_test.go
descope/client/config.go
descope/internal/auth/auth.go
descope/internal/utils/helpers.go
descope/types.go

https://github.com/descope/etc/issues/8683
Add `AuthManagementKey` to config and client to work with disabled APIs

Add `AuthManagementKey` to config and client

---

descope/api/client.go
descope/client/client.go
descope/internal/auth/auth.go
descope/internal/auth/jwt.go
descope/internal/mgmt/jwt.go
descope/internal/mgmt/jwt_test.go
descope/internal/mgmt/mgmt.go
descope/internal/mgmt/mgmt_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go

This allows mgmt SDK to create a jwt via one call to descope backend
+ tests 
related to https://github.com/descope/etc/issues/9139

Signup or in via mgmt

---

README.md
descope/internal/mgmt/project.go
descope/internal/mgmt/project_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go

- Add export snapshot request parameter.
This is a minor breaking change as the `ExportSnapshot` function now expects another parameter. Calls such as:
```go
descopeClient.Management.Project().ExportSnapshot(ctx)
```
will need to be updated as follows:
```go
descopeClient.Management.Project().ExportSnapshot(ctx, nil)
```

Add export snapshot request parameter

---

README.md

tenant name isn't part of the func
https://docs.descope.com/tenant-management/sdks#create-tenant

Update README.md - fix redundant arg

---

descope/types.go

- Add support for importing argon2 password hashes

Add support for importing argon2 password hashes

---

descope/gin/go.mod
go.mod

This PR removes the `toolchain go1.24.1` directive from the `go.mod` file.
**Reasoning:**
* The `toolchain` directive was likely added unintentionally due to Go tooling behavior prior to Go 1.25 (related to Go issue https://github.com/golang/go/issues/65847), where `go mod` commands could automatically add it based on the local environment.
* Specifying a toolchain version in a library forces consumers to adopt at least that toolchain version (1.24.1), which is often undesirable and unnecessary.
* The SDK's actual requirement is Go language version 1.23, as specified by the `go 1.23` directive.
**Impact:**
By removing this line, consumers of the SDK will only be constrained by the `go 1.23` language version requirement and can use any compatible Go toolchain (Go 1.23 or newer) without …

fix: Remove unnecessary toolchain directive forcing Go 1.24.1

---

.gitignore
descope/internal/mgmt/tenant.go
descope/internal/mgmt/tenant_test.go
descope/types.go

Related: https://github.com/descope/etc/issues/8356
Related: https://github.com/descope/etc/issues/249
Added fields to create/update tenant API:
- EnforceSSO
- Disabled

Add EnforceSSO, Disabled fields in tenant API

---

descope/types.go

Add more options to role search, so now all roles available on tenant are loadable in single request 
Add template ID and provider ID to update user requests
related to https://github.com/descope/etc/issues/10011
related to https://github.com/descope/etc/issues/10155

Extend different Descope Types

---

descope/api/client.go
descope/api/client_test.go

https://github.com/descope/etc/issues/10013
Add project ID header to default headers

Add project ID header

---

README.md
descope/internal/mgmt/jwt.go
descope/internal/mgmt/jwt_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go
descope/types.go

For SDK calls initiated by MGMT SDK
related to https://github.com/descope/etc/issues/10354 Breaks compilation

Allow custom refresh token duration

---

README.md
descope/internal/auth/oauth.go
descope/internal/auth/oauth_test.go
descope/internal/auth/sso.go
descope/internal/auth/sso_test.go
descope/sdk/auth.go
descope/tests/mocks/auth/authenticationmock.go
descope/tests/mocks/auth/authenticationmock_test.go
examples/webapp/main.go

https://github.com/descope/etc/issues/9752
https://github.com/descope/etc/issues/10809
Add login hint support for SSO and OAuth.
Note: Breaking compilation.

Add login hint support for SSO and OAuth

---

descope/api/client.go
descope/authztypes.go
descope/internal/mgmt/fga.go
descope/internal/mgmt/fga_test.go
descope/sdk/mgmt.go
descope/tests/mocks/mgmt/managementmock.go

Required for: 
- https://github.com/descope/etc/issues/11356
Performs a "dry run" for saving a schema:
1. Validates the schema.
2. Calculates if any "types" or "relations" from the current schema might get deleted as a result of performing this change.
3. The `dryrun` calls does **not** make any changes to the schema or relations.
Depends on:
- https://github.com/descope/managementservice/pull/2507

Save Schema "Dry Run" to Preview Deletes (GO-SDK)
